// Writes dist/_headers after the Astro build. Runs as npm's `postbuild`, the same way
// generate-agent-files.mjs runs as `prebuild`.
//
// The script-src hashes are computed from the built output rather than written by hand.
// Astro inlines its small script bundles, so the exact bytes change whenever a component's
// script changes -- a hand-maintained hash list would silently break the site on the next
// edit, which is worse than having no CSP at all.
//
// Hashes rather than 'unsafe-inline' is the whole point: 'unsafe-inline' would re-permit
// injected inline script and inline event handlers, i.e. exactly the payload shape the
// JSON-LD escaping fix was for. With hashes, an injected <img onerror=...> does not run.
//
// <script type="application/ld+json"> is deliberately not hashed. It is a data block, not
// executed, so script-src does not apply to it -- which matters here because its contents
// vary per page and hashing it would force per-path headers.

import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";

const dist = path.join(process.cwd(), "dist");
if (!fs.existsSync(dist)) throw new Error("dist/ not found — run the build first");

// Umami serves its script from one host and collects from another -- cloud.umami.is for the
// script, gateway.umami.is for the beacon. Allowing only the script host silently kills
// analytics with a console-only CSP error, so both are named.
const UMAMI_SCRIPT = "https://cloud.umami.is";
const UMAMI_COLLECT = "https://gateway.umami.is";
const GOOGLE_FONTS_CSS = "https://fonts.googleapis.com";
const GOOGLE_FONTS_FILES = "https://fonts.gstatic.com";
// Deliberately NOT allowed: static.cloudflareinsights.com, the Cloudflare Web Analytics
// beacon. Cloudflare injects it at the edge so it does not appear in the built HTML, and it
// gets blocked -- that is intended. Analytics here is Umami only. Turning Web Analytics off
// in the Cloudflare dashboard stops the injection and the console error along with it.

function htmlFiles(dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...htmlFiles(p));
    else if (entry.name.endsWith(".html")) out.push(p);
  }
  return out;
}

const pages = htmlFiles(dist);
const hashes = new Set();
const handlers = [];

for (const file of pages) {
  const html = fs.readFileSync(file, "utf8");
  for (const [, attrs, body] of html.matchAll(/<script([^>]*)>([\s\S]*?)<\/script>/g)) {
    if (/\ssrc=/.test(attrs) || /ld\+json/.test(attrs)) continue;
    hashes.add(`'sha256-${crypto.createHash("sha256").update(body, "utf8").digest("base64")}'`);
  }
  // An inline handler cannot be hashed, so one would be silently broken by this policy.
  // Fail the build instead of shipping a page whose behaviour the CSP quietly removes.
  for (const [, attr] of html.matchAll(/\s(on[a-z]+)=["']/gi)) {
    handlers.push(`${path.relative(dist, file)} ${attr}`);
  }
}

if (handlers.length) {
  throw new Error(
    `inline event handlers cannot be allowed by a hash-based CSP:\n  ${handlers.slice(0, 10).join("\n  ")}\n` +
      "Move the handler into a script block, or this page will not work once the CSP ships.",
  );
}

const csp = [
  "default-src 'self'",
  `script-src 'self' ${UMAMI_SCRIPT} ${[...hashes].sort().join(" ")}`,
  `style-src 'self' ${GOOGLE_FONTS_CSS}`,
  `font-src ${GOOGLE_FONTS_FILES}`,
  "img-src 'self' data:",
  `connect-src 'self' ${UMAMI_SCRIPT} ${UMAMI_COLLECT}`,
  "base-uri 'none'",
  "form-action 'none'",
  "frame-ancestors 'none'",
  "object-src 'none'",
  "upgrade-insecure-requests",
].join("; ");

const body = `# Generated by scripts/generate-csp.mjs on each build — do not edit by hand.
# The script-src hashes come from the built HTML, so they stay correct across edits.

/*
  Content-Security-Policy: ${csp}
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: geolocation=(), microphone=(), camera=(), payment=(), usb=()
  Cross-Origin-Opener-Policy: same-origin
`;

// Cloudflare caps a _headers line at 2,000 characters. Each script hash costs about 50, so
// this only becomes reachable if the site grows a lot of distinct inline scripts. Fail here
// rather than let the policy be truncated somewhere upstream where it would not be noticed.
const LINE_LIMIT = 2000;
for (const line of body.split("\n")) {
  if (line.length > LINE_LIMIT) {
    throw new Error(
      `_headers line is ${line.length} chars, over Cloudflare's ${LINE_LIMIT} limit:\n  ${line.slice(0, 120)}...\n` +
        "Reduce the number of distinct inline scripts, or move them to external files so script-src can be 'self'.",
    );
  }
}

fs.writeFileSync(path.join(dist, "_headers"), body);
console.log(
  `wrote dist/_headers — ${hashes.size} script hash(es) across ${pages.length} pages, ` +
    `longest line ${Math.max(...body.split("\n").map((l) => l.length))}/${LINE_LIMIT} chars`,
);
